name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set application-test.properties
        run: |
          mkdir -p src/test/resources
          cat <<EOF > src/test/resources/application-test.properties
          spring.flyway.enabled=false
          EOF

      - name: Set application.properties para ambiente de produção
        run: |
          mkdir -p src/main/resources
          cat <<EOF > src/main/resources/application.properties
          spring.datasource.url=${{ secrets.DATASOURCE_URL }}
          spring.datasource.username=${{ secrets.DATASOURCE_USERNAME }}
          spring.datasource.password=${{ secrets.DATASOURCE_PASSWORD }}
          spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

          spring.flyway.url=${{ secrets.FLYWAY_URL }}
          spring.flyway.user=${{ secrets.FLYWAY_USER }}
          spring.flyway.password=${{ secrets.FLYWAY_PASSWORD }}
          spring.flyway.locations=db/migrations
          spring.flyway.enabled=true

          spring.rabbitmq.addresses=${{ secrets.RABBITMQ_ADDRESSES }}
          broker.queue.user.name=${{ secrets.BROKER_QUEUE_USER_NAME }}
          EOF

      - name: Build and analyze 
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=FernandoCruzCavina_account-microservice \
            -Dsonar.organization=fernandocruzcavina \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}